<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PTS-LDR-1091L66" ignored="0" name="Verify Add to Cart Functionality" tests="1" failures="1" timestamp="2022-03-27T22:33:21 CDT" time="45.506" errors="0">
  <testcase name="VerifyCart" time="20.43" classname="Assesment.FlipKart.AddToCartPLPTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Assesment.FlipKart.AddToCartPLPTest.VerifyCart(AddToCartPLPTest.java:76)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- VerifyCart -->
</testsuite> <!-- Verify Add to Cart Functionality -->
