<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PTS-LDR-1091L66" ignored="0" name="Verify Add to Cart Functionality" tests="1" failures="1" timestamp="2022-03-27T22:31:25 CDT" time="55.071" errors="0">
  <testcase name="VerifyCart" time="17.603" classname="Assesment.FlipKart.AddToCartPLPTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Assesment.FlipKart.AddToCartPLPTest.VerifyCart(AddToCartPLPTest.java:76)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- VerifyCart -->
</testsuite> <!-- Verify Add to Cart Functionality -->
